name: main
on:
  push:
    branches:
      - main

jobs:

  build-and-publish-snap:
    name: Build and publish dive snap
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: snapcore/action-build@v1
        id: build
      - name: publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
